### ISSUE TITLE
tf clariah/wp6-missieven fails?

### ISSUE THREAD

**Issue by proycon** [CLARIAH/wp6-missieven#14]
I wanted to take a look at the text-fabric browser for the missieven, I made a virtualenv then followed the instructions in the README, `pip install text-fabric`, and:

```
$ tf clariah/wp6-missieven
This is Text-Fabric 12.5.3
Setting up TF browser for clariah/wp6-missieven  
**Locating corpus resources ...**
The requested app is not available offline
        ~/text-fabric-data/github/clariah/wp6-missieven/app not found
Status: latest release online v1.1e versus None locally
downloading app, main data and requested additions ...
Using app in ~/text-fabric-data/github/clariah/wp6-missieven/app:
        unknown release or commit (latest release)
The requested data is not available offline
        ~/text-fabric-data/github/clariah/wp6-missieven/tf not found
Status: latest release online v1.1e versus None locally
downloading app, main data and requested additions ...
Using data in ~/text-fabric-data/github/clariah/wp6-missieven/tf:
        unknown release or commit (latest release)
  0.00s Not all of the warp features otype and oslots are present in
~/text-fabric-data/github/clariah/wp6-missieven/tf
  0.00s Only the Feature and Edge APIs will be enabled
  0.00s Warp feature "otext" not found. Working without Text-API
Loading TF corpus data. Please wait ...
Traceback (most recent call last):
  File "/home/proycon/work/wp6-missieven/env/bin/tf", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/proycon/work/wp6-missieven/env/lib/python3.12/site-packages/tf/browser/start.py", line 245, in main
    webapp = setup(debug, *cargs)
             ^^^^^^^^^^^^^^^^^^^^
  File "/home/proycon/work/wp6-missieven/env/lib/python3.12/site-packages/tf/browser/web.py", line 253, in setup
    webapp = factory(web)
             ^^^^^^^^^^^^
  File "/home/proycon/work/wp6-missieven/env/lib/python3.12/site-packages/tf/browser/web.py", line 129, in factory
    app.register_blueprint(nerFactory(web))
                           ^^^^^^^^^^^^^^^
  File "/home/proycon/work/wp6-missieven/env/lib/python3.12/site-packages/tf/browser/ner/web.py", line 70, in factory
    web.ner = NER(tfApp, data=data, browse=True)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/proycon/work/wp6-missieven/env/lib/python3.12/site-packages/tf/browser/ner/ner.py", line 343, in __init__
    Sets.__init__(self, sets=data.sets)
  File "/home/proycon/work/wp6-missieven/env/lib/python3.12/site-packages/tf/browser/ner/sets.py", line 56, in __init__
    Data.__init__(self, sets=sets)
  File "/home/proycon/work/wp6-missieven/env/lib/python3.12/site-packages/tf/browser/ner/data.py", line 63, in __init__
    Corpus.__init__(self)
  File "/home/proycon/work/wp6-missieven/env/lib/python3.12/site-packages/tf/browser/ner/corpus.py", line 60, in __init__
    L = api.L
        ^^^^^
AttributeError: 'Api' object has no attribute 'L'
```

**Comment by proycon** [comment]
Btw, the README also mentions a demo at https://CLARIAH.github.io/wp6-missieven-search/, but that gives a  404.

**Comment by proycon** [comment]
I got it to work with the latest text-fabric and manually creating and linking ~/github/CLARIAH/wp6-missieven
